// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: stream/pb/stream.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StreamServiceClient is the client API for StreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamServiceClient interface {
	SendVideoStream(ctx context.Context, in *VStreamRequest, opts ...grpc.CallOption) (StreamService_SendVideoStreamClient, error)
}

type streamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamServiceClient(cc grpc.ClientConnInterface) StreamServiceClient {
	return &streamServiceClient{cc}
}

func (c *streamServiceClient) SendVideoStream(ctx context.Context, in *VStreamRequest, opts ...grpc.CallOption) (StreamService_SendVideoStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &StreamService_ServiceDesc.Streams[0], "/stream.StreamService/SendVideoStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamServiceSendVideoStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StreamService_SendVideoStreamClient interface {
	Recv() (*VStreamResponse, error)
	grpc.ClientStream
}

type streamServiceSendVideoStreamClient struct {
	grpc.ClientStream
}

func (x *streamServiceSendVideoStreamClient) Recv() (*VStreamResponse, error) {
	m := new(VStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamServiceServer is the server API for StreamService service.
// All implementations must embed UnimplementedStreamServiceServer
// for forward compatibility
type StreamServiceServer interface {
	SendVideoStream(*VStreamRequest, StreamService_SendVideoStreamServer) error
	mustEmbedUnimplementedStreamServiceServer()
}

// UnimplementedStreamServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStreamServiceServer struct {
}

func (UnimplementedStreamServiceServer) SendVideoStream(*VStreamRequest, StreamService_SendVideoStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SendVideoStream not implemented")
}
func (UnimplementedStreamServiceServer) mustEmbedUnimplementedStreamServiceServer() {}

// UnsafeStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamServiceServer will
// result in compilation errors.
type UnsafeStreamServiceServer interface {
	mustEmbedUnimplementedStreamServiceServer()
}

func RegisterStreamServiceServer(s grpc.ServiceRegistrar, srv StreamServiceServer) {
	s.RegisterService(&StreamService_ServiceDesc, srv)
}

func _StreamService_SendVideoStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(VStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamServiceServer).SendVideoStream(m, &streamServiceSendVideoStreamServer{stream})
}

type StreamService_SendVideoStreamServer interface {
	Send(*VStreamResponse) error
	grpc.ServerStream
}

type streamServiceSendVideoStreamServer struct {
	grpc.ServerStream
}

func (x *streamServiceSendVideoStreamServer) Send(m *VStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

// StreamService_ServiceDesc is the grpc.ServiceDesc for StreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stream.StreamService",
	HandlerType: (*StreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendVideoStream",
			Handler:       _StreamService_SendVideoStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "stream/pb/stream.proto",
}
